version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "composer dependencies"
    versioning-strategy: increase-if-necessary