name: Content Generation

on:
  schedule:
    - cron: '0 0 * * *' # everyday at midnight
    # - cron: '0 0 * * 1' # every Monday at midnight
    # - cron: '0 0 * * 3' # every Wednesday at midnight
    # - cron: '0 0 * * 0' # every Sunday at midnight
  workflow_dispatch:

permissions:
  models: read

jobs:
  content-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Generate Blog Post
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          # curl -H "Authorization: Bearer $GITHUB_TOKEN" \
          #     https://models.github.ai/catalog/models

          DAY=$(date +%u)
          if [ "$DAY" -eq 1 ]; then
            PROMPT="Write a detailed blog post about a technology topic (e.g., programming languages, frameworks, tools, or best practices) in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          elif [ "$DAY" -eq 2 ]; then
            PROMPT="Write a detailed blog post about a business topic (e.g., startups, entrepreneurship, management, or productivity) in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          elif [ "$DAY" -eq 3 ]; then
            PROMPT="Write a detailed blog post about a cryptocurrency topic (e.g., blockchain, DeFi, NFTs, or crypto trends) in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          elif [ "$DAY" -eq 4 ]; then
            PROMPT="Write a detailed blog post about software architecture or scalable systems in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          elif [ "$DAY" -eq 5 ]; then
            PROMPT="Write a detailed blog post about debugging strategies or code quality improvements in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          elif [ "$DAY" -eq 6 ]; then
            PROMPT="Write a detailed blog post about modern programming paradigms or workflow enhancements in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          else
            PROMPT="Write a detailed blog post about any trending topic in software engineering in markdown. Output in JSON using this structure { title: '  ', tags: [], content: '  '}"
          fi

          RESPONSE=$(curl "https://models.github.ai/inference/chat/completions" \
                      -H "Content-Type: application/json" \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -d "{\"messages\": [{\"role\": \"user\", \"content\": \"$PROMPT\"}], \"model\": \"openai/gpt-4.1\"}"
                    )
          MESSAGE=$(node -pe 'JSON.parse(process.argv[1]).choices[0].message.content' "$RESPONSE")
          TITLE=$(node -pe 'JSON.parse(process.argv[1]).title' "$MESSAGE" | sed 's/:/-/g')
          SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9 ]//g' | tr ' ' '-')
          CONTENT=$(node -pe 'JSON.parse(process.argv[1]).content' "$MESSAGE")

          mkdir blog/_posts/$SLUG
          cd blog/_posts/$SLUG
          
          {
          echo "---"
          echo "title: $TITLE"
          echo "date: $(date +%F)"
          echo "author: mrepol742"
          echo "tags:"
          node -e 'JSON.parse(process.argv[1]).tags.forEach(tag => console.log("  - " + tag))' "$MESSAGE"
          echo "meta:"
          echo "  - name: twitter:creator"
          echo "    content: '@mrepol742'"
          echo "  - name: twitter:title"
          echo "    content: $TITLE"
          echo "  - property: og:title"
          echo "    content: $TITLE"
          echo "  - name: author"
          echo "    content: mrepol742"
          echo "  - name: keywords"
          echo "    content: $(node -pe 'JSON.parse(process.argv[1]).tags.join(", ")' "$MESSAGE")"
          echo "  - property: og:url"
          echo "    content: https://mrepol742-blog.vercel.app/$SLUG/"
          echo "  - rel: canonical"
          echo "    href: https://mrepol742-blog.vercel.app/$SLUG/"
          echo "---"
          echo ""
          } > index.md

          echo "$CONTENT" >> index.md
          echo "$TITLE" > /tmp/generated_blog_title.txt

          cat index.md
          
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          TITLE=$(cat /tmp/generated_blog_title.txt)
          git add .
          git commit -m "Add new blog post: $TITLE" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
